**4.1**

In [ ]:
# Task 1: Measurement
def convert_length(value, from_unit, to_unit):
    # Conversion factors
    METER_TO_FEET = 3.28084

    if from_unit == 'm' and to_unit == 'ft':
        return value * METER_TO_FEET
    elif from_unit == 'ft' and to_unit == 'm':
        return value / METER_TO_FEET
    else:
        raise ValueError("Unsupported length unit conversion. Please use 'm' or 'ft'.")

def convert_weight(value, from_unit, to_unit):
    # Conversion factors
    KG_TO_LBS = 2.20462

    if from_unit == 'kg' and to_unit == 'lbs':
        return value * KG_TO_LBS
    elif from_unit == 'lbs' and to_unit == 'kg':
        return value / KG_TO_LBS
    else:
        raise ValueError("Unsupported weight unit conversion. Please use 'kg' or 'lbs'.")

def convert_volume(value, from_unit, to_unit):
    # Conversion factors
    LITER_TO_GALLON = 0.264172

    if from_unit == 'L' and to_unit == 'gal':
        return value * LITER_TO_GALLON
    elif from_unit == 'gal' and to_unit == 'L':
        return value / LITER_TO_GALLON
    else:
        raise ValueError("Unsupported volume unit conversion. Please use 'L' or 'gal'.")

def run_converter():
    print("Welcome to the Unit Converter!")

    while True:
        print("\nChoose a conversion type:")
        print("1. Length (meters <-> feet)")
        print("2. Weight (kilograms <-> pounds)")
        print("3. Volume (liters <-> gallons)")
        print("4. Exit")

        choice = input("Enter your choice (1-4): ")

        if choice == '4':
            print("Exiting Unit Converter. Goodbye!")
            break

        conversion_function = None
        from_unit_options = []
        to_unit_options = []
        unit_prompt = ""

        if choice == '1':
            conversion_function = convert_length
            from_unit_options = ['m', 'ft']
            to_unit_options = ['m', 'ft']
            unit_prompt = "Enter the unit to convert FROM (m for meters, ft for feet): "
        elif choice == '2':
            conversion_function = convert_weight
            from_unit_options = ['kg', 'lbs']
            to_unit_options = ['kg', 'lbs']
            unit_prompt = "Enter the unit to convert FROM (kg for kilograms, lbs for pounds): "
        elif choice == '3':
            conversion_function = convert_volume
            from_unit_options = ['L', 'gal']
            to_unit_options = ['L', 'gal']
            unit_prompt = "Enter the unit to convert FROM (L for liters, gal for gallons): "
        else:
            print("Invalid choice. Please enter a number between 1 and 4.")
            continue

        try:
            value_str = input("Enter the value to convert: ")
            value = float(value_str)

            from_unit = input(unit_prompt).lower()
            if from_unit not in from_unit_options:
                print(f"Invalid 'from' unit. Please choose from {', '.join(from_unit_options)}.")
                continue

            to_unit = input(f"Enter the unit to convert TO ({' or '.join([u for u in to_unit_options if u != from_unit])}): ").lower()
            if to_unit not in to_unit_options or to_unit == from_unit:
                print(f"Invalid 'to' unit or same as 'from' unit. Please choose from {', '.join(to_unit_options)} and not '{from_unit}'.")
                continue

            result = conversion_function(value, from_unit, to_unit)
            print(f"{value} {from_unit} is equal to {result:.4f} {to_unit}.")

        except ValueError as e:
            print(f"Error: Invalid input. {e}")
        except Exception as e:
            print(f"An unexpected error occurred: {e}")

# Run the converter
run_converter()

Welcome to the Unit Converter!

Choose a conversion type:
1. Length (meters <-> feet)
2. Weight (kilograms <-> pounds)
3. Volume (liters <-> gallons)
4. Exit
Enter your choice (1-4): 1
Enter the value to convert: 10
Enter the unit to convert FROM (m for meters, ft for feet): m
Enter the unit to convert TO (ft): ft
10.0 m is equal to 32.8084 ft.

Choose a conversion type:
1. Length (meters <-> feet)
2. Weight (kilograms <-> pounds)
3. Volume (liters <-> gallons)
4. Exit
Enter your choice (1-4): 4
Exiting Unit Converter. Goodbye!


In [ ]:
# Task 2: Mathematical Expression
def calculate_sum(numbers):
    if not numbers:
        raise ValueError("The list of numbers cannot be empty.")
    return sum(numbers)

def calculate_average(numbers):
    """
    Calculates the average of a list of numbers.

    Args:
        numbers (list): A list of numeric values.

    Returns:
        float: The average of the numbers.

    Raises:
        ValueError: If the list is empty.
    """
    if not numbers:
        raise ValueError("The list of numbers cannot be empty to calculate the average.")
    return sum(numbers) / len(numbers)

def find_maximum(numbers):
    """
    Finds the maximum value in a list of numbers.

    Args:
        numbers (list): A list of numeric values.

    Returns:
        float: The maximum value in the list.

    Raises:
        ValueError: If the list is empty.
    """
    if not numbers:
        raise ValueError("The list of numbers cannot be empty to find the maximum.")
    return max(numbers)

def find_minimum(numbers):
    """
    Finds the minimum value in a list of numbers.

    Args:
        numbers (list): A list of numeric values.

    Returns:
        float: The minimum value in the list.

    Raises:
        ValueError: If the list is empty.
    """
    if not numbers:
        raise ValueError("The list of numbers cannot be empty to find the minimum.")
    return min(numbers)

def run_math_operations():
    """
    Main function to run the mathematical operations program.
    Prompts the user for an operation and a list of numbers, then displays the result.
    Handles potential errors such as invalid input or empty lists.
    """
    print("Welcome to the Mathematical Operations Program!")

    while True:
        print("\nChoose an operation:")
        print("1. Sum")
        print("2. Average")
        print("3. Maximum")
        print("4. Minimum")
        print("5. Exit")

        choice = input("Enter your choice (1-5): ")

        if choice == '5':
            print("Exiting program. Goodbye!")
            break

        if choice not in ['1', '2', '3', '4']:
            print("Invalid choice. Please enter a number between 1 and 5.")
            continue

        try:
            numbers_str = input("Enter a list of numbers separated by spaces: ")
            if not numbers_str.strip():
                raise ValueError("No numbers entered. The list cannot be empty.")

            numbers = [float(x) for x in numbers_str.split()]

            result = None
            operation_name = ""

            if choice == '1':
                result = calculate_sum(numbers)
                operation_name = "Sum"
            elif choice == '2':
                result = calculate_average(numbers)
                operation_name = "Average"
            elif choice == '3':
                result = find_maximum(numbers)
                operation_name = "Maximum"
            elif choice == '4':
                result = find_minimum(numbers)
                operation_name = "Minimum"

            print(f"The {operation_name} of the numbers is: {result}")

        except ValueError as e:
            print(f"Error: Invalid input. {e}")
        except Exception as e:
            print(f"An unexpected error occurred: {e}")

# Run the program
run_math_operations()

Welcome to the Mathematical Operations Program!

Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
5. Exit
Enter your choice (1-5): 1
Enter a list of numbers separated by spaces: 10 5
The Sum of the numbers is: 15.0

Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
5. Exit
Enter your choice (1-5): 5
Exiting program. Goodbye!


**4.2**

In [ ]:
def extract_every_other(lst):
    return lst[::2]

my_list = [1, 2, 3, 4, 5, 6]
extracted_list = extract_every_other(my_list)
print(f"Original list: {my_list}")
print(f"Every other element: {extracted_list}")

my_list_2 = ['a', 'b', 'c', 'd', 'e']
extracted_list_2 = extract_every_other(my_list_2)
print(f"Original list: {my_list_2}")
print(f"Every other element: {extracted_list_2}")

Original list: [1, 2, 3, 4, 5, 6]
Every other element: [1, 3, 5]
Original list: ['a', 'b', 'c', 'd', 'e']
Every other element: ['a', 'c', 'e']


In [ ]:
# 3. Reverse a List using Slicing
def get_sublist(lst, start, end):
    if not (0 <= start <= end < len(lst)):
        raise IndexError("Start or end index is out of bounds or start is greater than end.")
    return lst[start : end + 1]

my_list = [1, 2, 3, 4, 5, 6]
sub_list = get_sublist(my_list, 2, 4)
print(f"Original list: {my_list}")
print(f"Sublist from index 2 to 4 (inclusive): {sub_list}")

my_list_2 = ['a', 'b', 'c', 'd', 'e']
sub_list_2 = get_sublist(my_list_2, 0, 2)
print(f"Original list: {my_list_2}")
print(f"Sublist from index 0 to 2 (inclusive): {sub_list_2}")

Original list: [1, 2, 3, 4, 5, 6]
Sublist from index 2 to 4 (inclusive): [3, 4, 5]
Original list: ['a', 'b', 'c', 'd', 'e']
Sublist from index 0 to 2 (inclusive): ['a', 'b', 'c']


In [ ]:
# 4. Remove First and Last Elements
def remove_first_last(lst):
    if len(lst) < 3:
        raise ValueError("List must contain at least 3 elements to remove the first and last.")
    return lst[1:-1]

# Example usage:
my_list = [1, 2, 3, 4, 5]
modified_list = remove_first_last(my_list)
print(f"Original list: {my_list}")
print(f"List after removing first and last elements: {modified_list}")

my_list_2 = ['a', 'b', 'c', 'd', 'e']
modified_list_2 = remove_first_last(my_list_2)
print(f"Original list: {my_list_2}")
print(f"List after removing first and last elements: {modified_list_2}")

try:
    my_list_short = [1, 2]
    remove_first_last(my_list_short)
except ValueError as e:
    print(f"Error for short list: {e}")

Original list: [1, 2, 3, 4, 5]
List after removing first and last elements: [2, 3, 4]
Original list: ['a', 'b', 'c', 'd', 'e']
List after removing first and last elements: ['b', 'c', 'd']
Error for short list: List must contain at least 3 elements to remove the first and last.


In [ ]:
# 5. Get the First n Elements:
def get_first_n(lst, n):
    if n < 0:
        raise ValueError("n must be a non-negative integer.")
    return lst[:n]

my_list = [1, 2, 3, 4, 5, 6, 7, 8]
num_elements = 3
first_n_elements = get_first_n(my_list, num_elements)
print(f"Original list: {my_list}")
print(f"First {num_elements} elements: {first_n_elements}")

my_list_2 = ['a', 'b', 'c', 'd', 'e']
num_elements_2 = 2
first_n_elements_2 = get_first_n(my_list_2, num_elements_2)
print(f"Original list: {my_list_2}")
print(f"First {num_elements_2} elements: {first_n_elements_2}")

num_elements_3 = 10
first_n_elements_3 = get_first_n(my_list, num_elements_3)
print(f"Original list: {my_list}")
print(f"First {num_elements_3} elements (n > len(lst)): {first_n_elements_3}")

num_elements_4 = 0
first_n_elements_4 = get_first_n(my_list, num_elements_4)
print(f"Original list: {my_list}")
print(f"First {num_elements_4} elements: {first_n_elements_4}")

try:
    get_first_n(my_list, -1)
except ValueError as e:
    print(f"Error for negative n: {e}")

Original list: [1, 2, 3, 4, 5, 6, 7, 8]
First 3 elements: [1, 2, 3]
Original list: ['a', 'b', 'c', 'd', 'e']
First 2 elements: ['a', 'b']
Original list: [1, 2, 3, 4, 5, 6, 7, 8]
First 10 elements (n > len(lst)): [1, 2, 3, 4, 5, 6, 7, 8]
Original list: [1, 2, 3, 4, 5, 6, 7, 8]
First 0 elements: []
Error for negative n: n must be a non-negative integer.


In [ ]:
# 6. Extract Elements from the End:
def get_last_n(lst, n):
    if n < 0:
        raise ValueError("n must be a non-negative integer.")
    return lst[-n:]

my_list = [1, 2, 3, 4, 5, 6, 7, 8]
num_elements = 3
last_n_elements = get_last_n(my_list, num_elements)
print(f"Original list: {my_list}")
print(f"Last {num_elements} elements: {last_n_elements}")

my_list_2 = ['a', 'b', 'c', 'd', 'e']
num_elements_2 = 2
last_n_elements_2 = get_last_n(my_list_2, num_elements_2)
print(f"Original list: {my_list_2}")
print(f"Last {num_elements_2} elements: {last_n_elements_2}")

num_elements_3 = 10
last_n_elements_3 = get_last_n(my_list, num_elements_3)
print(f"Original list: {my_list}")
print(f"Last {num_elements_3} elements (n > len(lst)): {last_n_elements_3}")

num_elements_4 = 0
last_n_elements_4 = get_last_n(my_list, num_elements_4)
print(f"Original list: {my_list}")
print(f"Last {num_elements_4} elements: {last_n_elements_4}")

try:
    get_last_n(my_list, -1)
except ValueError as e:
    print(f"Error for negative n: {e}")

Original list: [1, 2, 3, 4, 5, 6, 7, 8]
Last 3 elements: [6, 7, 8]
Original list: ['a', 'b', 'c', 'd', 'e']
Last 2 elements: ['d', 'e']
Original list: [1, 2, 3, 4, 5, 6, 7, 8]
Last 10 elements (n > len(lst)): [1, 2, 3, 4, 5, 6, 7, 8]
Original list: [1, 2, 3, 4, 5, 6, 7, 8]
Last 0 elements: [1, 2, 3, 4, 5, 6, 7, 8]
Error for negative n: n must be a non-negative integer.


In [ ]:
# 7. Extract Elements in Reverse Order
def reverse_skip(lst):
    # Start from the second-to-last element (index -2) and step backward by 2
    return lst[-2::-2]

my_list = [1, 2, 3, 4, 5, 6]
reversed_skipped_list = reverse_skip(my_list)
print(f"Original list: {my_list}")
print(f"Reversed and skipped elements: {reversed_skipped_list}")

my_list_2 = [10, 20, 30, 40, 50]
reversed_skipped_list_2 = reverse_skip(my_list_2)
print(f"Original list: {my_list_2}")
print(f"Reversed and skipped elements: {reversed_skipped_list_2}")

my_list_3 = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
reversed_skipped_list_3 = reverse_skip(my_list_3)
print(f"Original list: {my_list_3}")
print(f"Reversed and skipped elements: {reversed_skipped_list_3}")

Original list: [1, 2, 3, 4, 5, 6]
Reversed and skipped elements: [5, 3, 1]
Original list: [10, 20, 30, 40, 50]
Reversed and skipped elements: [40, 20]
Original list: ['a', 'b', 'c', 'd', 'e', 'f', 'g']
Reversed and skipped elements: ['f', 'd', 'b']


**4.3 Exercise on Nested List:**

In [ ]:
# 1. Flatten a Nested List:
def flatten(lst):
    flattened_list = []
    for item in lst:
        if isinstance(item, list):
            flattened_list.extend(flatten(item))
        else:
            flattened_list.append(item)
    return flattened_list

nested_list_1 = [[1, 2], [3, 4], [5]]
print(f"Original nested list: {nested_list_1}")
print(f"Flattened list: {flatten(nested_list_1)}")

nested_list_2 = [1, [2, [3, 4]], 5]
print(f"Original nested list: {nested_list_2}")
print(f"Flattened list: {flatten(nested_list_2)}")

Original nested list: [[1, 2], [3, 4], [5]]
Flattened list: [1, 2, 3, 4, 5]
Original nested list: [1, [2, [3, 4]], 5]
Flattened list: [1, 2, 3, 4, 5]


In [ ]:
# 2. Accessing Nested List Elements:
def access_nested_element(lst, indices):
    current_element = lst
    for index in indices:
        if not isinstance(current_element, list) or not (0 <= index < len(current_element)):
            raise IndexError(f"Invalid index {index} for current element {current_element}")
        current_element = current_element[index]
    return current_element

nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices_1 = [1, 2]
element_1 = access_nested_element(nested_list, indices_1)
print(f"Original nested list: {nested_list}")
print(f"Element at indices {indices_1}: {element_1}")

indices_2 = [0, 1]
element_2 = access_nested_element(nested_list, indices_2)
print(f"Element at indices {indices_2}: {element_2}")

nested_list_deep = [1, [2, [3, 4]], 5]
indices_3 = [1, 1, 0]
element_3 = access_nested_element(nested_list_deep, indices_3)
print(f"Original nested list: {nested_list_deep}")
print(f"Element at indices {indices_3}: {element_3}")

try:
    access_nested_element(nested_list, [1, 3])
except IndexError as e:
    print(f"Error: {e}")

try:
    access_nested_element(nested_list, [3, 0])
except IndexError as e:
    print(f"Error: {e}")

Original nested list: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Element at indices [1, 2]: 6
Element at indices [0, 1]: 2
Original nested list: [1, [2, [3, 4]], 5]
Element at indices [1, 1, 0]: 3
Error: Invalid index 3 for current element [4, 5, 6]
Error: Invalid index 3 for current element [[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:
# 3. Sum of All Elements in a Nested List:
def sum_nested(lst):
    total_sum = 0
    for item in lst:
        if isinstance(item, list):
            total_sum += sum_nested(item)
        elif isinstance(item, (int, float)):
            total_sum += item
    return total_sum

nested_list_1 = [[1, 2], [3, [4, 5]], 6]
print(f"Original nested list: {nested_list_1}")
print(f"Sum of all elements: {sum_nested(nested_list_1)}")

nested_list_2 = [10, [20, 30], [40, [50]]]
print(f"Original nested list: {nested_list_2}")
print(f"Sum of all elements: {sum_nested(nested_list_2)}")

nested_list_3 = [1]
print(f"Original nested list: {nested_list_3}")
print(f"Sum of all elements: {sum_nested(nested_list_3)}")

nested_list_4 = []
print(f"Original nested list: {nested_list_4}")
print(f"Sum of all elements: {sum_nested(nested_list_4)}")

Original nested list: [[1, 2], [3, [4, 5]], 6]
Sum of all elements: 21
Original nested list: [10, [20, 30], [40, [50]]]
Sum of all elements: 150
Original nested list: [1]
Sum of all elements: 1
Original nested list: []
Sum of all elements: 0


In [ ]:
# 4. Remove Specific Element from a Nested List:
def remove_element(lst, elem):
    new_list = []
    for item in lst:
        if isinstance(item, list):
            modified_sublist = remove_element(item, elem)
            if modified_sublist:
                new_list.append(modified_sublist)
        elif item != elem:
            new_list.append(item)
    return new_list

nested_list_1 = [[1, 2], [3, 2], [4, 5]]
elem_1 = 2
modified_list_1 = remove_element(nested_list_1, elem_1)
print(f"Original nested list: {nested_list_1}")
print(f"After removing {elem_1}: {modified_list_1}")

nested_list_2 = [1, [2, [3, 2, 4]], 2, 5]
elem_2 = 2
modified_list_2 = remove_element(nested_list_2, elem_2)
print(f"Original nested list: {nested_list_2}")
print(f"After removing {elem_2}: {modified_list_2}")

nested_list_3 = [[1, 1], [1, 1]]
elem_3 = 1
modified_list_3 = remove_element(nested_list_3, elem_3)
print(f"Original nested list: {nested_list_3}")
print(f"After removing {elem_3}: {modified_list_3}")

nested_list_4 = [[], [1, [2]]]
elem_4 = 1
modified_list_4 = remove_element(nested_list_4, elem_4)
print(f"Original nested list: {nested_list_4}")
print(f"After removing {elem_4}: {modified_list_4}")

Original nested list: [[1, 2], [3, 2], [4, 5]]
After removing 2: [[1], [3], [4, 5]]
Original nested list: [1, [2, [3, 2, 4]], 2, 5]
After removing 2: [1, [[3, 4]], 5]
Original nested list: [[1, 1], [1, 1]]
After removing 1: []
Original nested list: [[], [1, [2]]]
After removing 1: [[[2]]]


In [ ]:
# 5. Find the Maximum Element in a Nested List:
def find_max(lst):
    max_val = float('-inf') # Initialize with negative infinity
    found_numeric = False

    for item in lst:
        if isinstance(item, list):
            try:
                nested_max = find_max(item)
                if nested_max is not None:
                    max_val = max(max_val, nested_max)
                    found_numeric = True
            except ValueError: #
                pass
        elif isinstance(item, (int, float)):
            max_val = max(max_val, item)
            found_numeric = True

    if not found_numeric:
        raise ValueError("The list is empty or contains no comparable numeric elements.")

    if max_val == float('-inf') and not found_numeric:
         raise ValueError("The list is empty or contains no comparable numeric elements.")

    return max_val

nested_list_1 = [[1, 2], [3, [4, 5]], 6]
print(f"Original nested list: {nested_list_1}")
print(f"Maximum element: {find_max(nested_list_1)}")

nested_list_2 = [10, [20, 300], [40, [50]]]
print(f"Original nested list: {nested_list_2}")
print(f"Maximum element: {find_max(nested_list_2)}")

nested_list_3 = [7]
print(f"Original nested list: {nested_list_3}")
print(f"Maximum element: {find_max(nested_list_3)}")

try:
    find_max([])
except ValueError as e:
    print(f"Error for empty list: {e}")

try:
    find_max([['a', 'b'], ['c']])
except ValueError as e:
    print(f"Error for non-numeric list: {e}")

nested_list_4 = [1, 'a', [2, 'b', [3]]]
print(f"Original nested list: {nested_list_4}")
print(f"Maximum numeric element: {find_max(nested_list_4)}")

Original nested list: [[1, 2], [3, [4, 5]], 6]
Maximum element: 6
Original nested list: [10, [20, 300], [40, [50]]]
Maximum element: 300
Original nested list: [7]
Maximum element: 7
Error for empty list: The list is empty or contains no comparable numeric elements.
Error for non-numeric list: The list is empty or contains no comparable numeric elements.
Original nested list: [1, 'a', [2, 'b', [3]]]
Maximum numeric element: 3


In [ ]:
# 6. Count Occurrences of an Element in a Nested List:
def count_occurrences(lst, elem):
    """
    Counts how many times a specific element appears in a nested list.

    Args:
        lst (list): The nested list to search.
        elem (any): The element to count.

    Returns:
        int: The number of occurrences of the element.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

nested_list_1 = [[1, 2], [2, 3], [2, 4]]
elem_1 = 2
print(f"Original nested list: {nested_list_1}")
print(f"Occurrences of {elem_1}: {count_occurrences(nested_list_1, elem_1)}")

nested_list_2 = [1, [2, [3, 2, 4]], 2, 5]
elem_2 = 2
print(f"Original nested list: {nested_list_2}")
print(f"Occurrences of {elem_2}: {count_occurrences(nested_list_2, elem_2)}")

nested_list_3 = ['a', ['b', ['a', 'c']], 'a']
elem_3 = 'a'
print(f"Original nested list: {nested_list_3}")
print(f"Occurrences of {elem_3}: {count_occurrences(nested_list_3, elem_3)}")

nested_list_4 = []
elem_4 = 1
print(f"Original nested list: {nested_list_4}")
print(f"Occurrences of {elem_4}: {count_occurrences(nested_list_4, elem_4)}")

Original nested list: [[1, 2], [2, 3], [2, 4]]
Occurrences of 2: 3
Original nested list: [1, [2, [3, 2, 4]], 2, 5]
Occurrences of 2: 3
Original nested list: ['a', ['b', ['a', 'c']], 'a']
Occurrences of a: 3
Original nested list: []
Occurrences of 1: 0


## 10.1 Basic Vector and Matrix Operation with Numpy.
### Problem - 1: Array Creation:

In [ ]:
import numpy as np

# 1. Initialize an empty array with size 2x2.
empty_array = np.empty((2, 2))
print(f"1. Empty 2x2 array:\n{empty_array}")

# 2. Initialize an all-one array with size 4x2.
ones_array = np.ones((4, 2))
print(f"\n2. All-ones 4x2 array:\n{ones_array}")

# 3. Return a new array of given shape and type, filled with fill value.
filled_array = np.full((3, 3), 7)
print(f"\n3. 3x3 array filled with 7s:\n{filled_array}")

# 4. Return a new array of zeros with same shape and type as a given array.
some_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(some_array)
print(f"\n4. Zeros like original array (shape {some_array.shape}):\n{zeros_like_array}")

# 5. Return a new array of ones with same shape and type as a given array.
ones_like_array = np.ones_like(some_array)
print(f"\n5. Ones like original array (shape {some_array.shape}):\n{ones_like_array}")

# 6. For an existing list new_list = [1,2,3,4] convert to a numpy array.
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print(f"\n6. List {new_list} converted to NumPy array:\n{numpy_array}")

1. Empty 2x2 array:
[[4.38488707e-315 0.00000000e+000]
 [2.14321575e-312 1.19069821e-321]]

2. All-ones 4x2 array:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. 3x3 array filled with 7s:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros like original array (shape (2, 2)):
[[0 0]
 [0 0]]

5. Ones like original array (shape (2, 2)):
[[1 1]
 [1 1]]

6. List [1, 2, 3, 4] converted to NumPy array:
[1 2 3 4]


### Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [ ]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49.
range_array = np.arange(10, 50)
print(f"1. Array with values from 10 to 49:\n{range_array}")

# 2. Create a 3x3 matrix with values ranging from 0 to 8.
matrix_3x3 = np.arange(9).reshape(3, 3)
print(f"\n2. 3x3 matrix with values from 0 to 8:\n{matrix_3x3}")

# 3. Create a 3x3 identity matrix.
identity_matrix = np.eye(3)
print(f"\n3. 3x3 Identity matrix:\n{identity_matrix}")

# 4. Create a random array of size 30 and find the mean of the array.
random_array_30 = np.random.random(30)
print(f"\n4. Random array of size 30 (first 5 elements):\n{random_array_30[:5]}...")
print(f"Mean of random array: {random_array_30.mean():.4f}")

# 5. Create a 10x10 array with random values and find the minimum and maximum values.
random_matrix_10x10 = np.random.random((10, 10))
print(f"\n5. 10x10 random array (top-left 3x3):\n{random_matrix_10x10[:3, :3]}...")
print(f"Minimum value: {random_matrix_10x10.min():.4f}")
print(f"Maximum value: {random_matrix_10x10.max():.4f}")

# 6. Create a zero array of size 10 and replace the 5th element with 1.
zero_array_10 = np.zeros(10)
zero_array_10[4] = 1 # 5th element is at index 4
print(f"\n6. Zero array of size 10 with 5th element replaced by 1:\n{zero_array_10}")

# 7. Reverse an array arr = [1,2,0,0,4,0].
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(f"\n7. Original array {arr}, reversed: {reversed_arr}")

# 8. Create a 2d array with 1 on the border and 0 inside.
# Example: 5x5 array
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print(f"\n8. 2D array with 1 on border and 0 inside (5x5):\n{border_array}")

# 9. Create an 8x8 matrix and fill it with a checkerboard pattern.
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1 # Odd rows, even columns
checkerboard[::2, 1::2] = 1 # Even rows, odd columns
print(f"\n9. 8x8 checkerboard matrix:\n{checkerboard}")

1. Array with values from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array of size 30 (first 5 elements):
[0.55622823 0.07803163 0.3866354  0.34458471 0.29180951]...
Mean of random array: 0.4689

5. 10x10 random array (top-left 3x3):
[[0.59731751 0.08006315 0.88593465]
 [0.81478332 0.89839934 0.27270272]
 [0.87315489 0.82812461 0.77832564]]...
Minimum value: 0.0028
Maximum value: 0.9867

6. Zero array of size 10 with 5th element replaced by 1:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Original array [1 2 0 0 4 0], reversed: [0 4 0 0 2 1]

8. 2D array with 1 on border and 0 inside (5x5):
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9. 8x8 checkerboard matrix:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 

### Problem - 3: Array Operations:

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print(f"Given arrays:\nx = \n{x}\ny = \n{y}\nv = {v}\nw = {w}")

# 1. Add the two arrays (x and y).
sum_xy = x + y
print(f"\n1. Sum of x and y:\n{sum_xy}")

# 2. Subtract the two arrays (x and y).
diff_xy = x - y
print(f"\n2. Difference of x and y:\n{diff_xy}")

# 3. Multiply the array with any integers of your choice (e.g., x * 3).
product_x_int = x * 3
print(f"\n3. x multiplied by 3:\n{product_x_int}")

# 4. Find the square of each element of the array (e.g., of x).
square_x = x**2
print(f"\n4. Square of each element in x:\n{square_x}")

# 5. Find the dot product between: v and w; x and v; x and y.
dot_vw = np.dot(v, w)
print(f"\n5. Dot product of v and w: {dot_vw}")
dot_xv = np.dot(x, v)
print(f"Dot product of x and v:\n{dot_xv}")
dot_xy = np.dot(x, y)
print(f"Dot product of x and y:\n{dot_xy}")

# 6. Concatenate x and y along row and Concatenate v and w along column.
concat_xy_row = np.concatenate((x, y), axis=0) # or np.vstack((x, y))
print(f"\n6. Concatenate x and y along row (axis=0):\n{concat_xy_row}")

concat_vw_col = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1) # or np.hstack((v.reshape(-1, 1), w.reshape(-1, 1)))
# Note: v and w are 1D arrays, for column concatenation they need to be 2D.
print(f"Concatenate v and w along column (axis=1):\n{concat_vw_col}")

# 7. Concatenate x and v; observe and explain why you get an error.
print(f"\n7. Attempting to concatenate x and v:")
try:
    np.concatenate((x, v), axis=0)
except ValueError as e:
    print(f"Error: {e}")


Given arrays:
x = 
[[1 2]
 [3 5]]
y = 
[[5 6]
 [7 8]]
v = [ 9 10]
w = [11 12]

1. Sum of x and y:
[[ 6  8]
 [10 13]]

2. Difference of x and y:
[[-4 -4]
 [-4 -3]]

3. x multiplied by 3:
[[ 3  6]
 [ 9 15]]

4. Square of each element in x:
[[ 1  4]
 [ 9 25]]

5. Dot product of v and w: 219
Dot product of x and v:
[29 77]
Dot product of x and y:
[[19 22]
 [50 58]]

6. Concatenate x and y along row (axis=0):
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along column (axis=1):
[[ 9 11]
 [10 12]]

7. Attempting to concatenate x and v:
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


### Problem - 4: Matrix Operations:

In [ ]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

print(f"Given matrices:\nA = \n{A}\nB = \n{B}")

# 1. Prove A.A⁻¹ = I.
inverse_A = np.linalg.inv(A)
product_A_invA = np.dot(A, inverse_A)
identity_matrix = np.eye(2)

print(f"\n1. Proving A.A⁻¹ = I:")
print(f"Inverse of A:\n{inverse_A}")
print(f"A . A⁻¹:\n{product_A_invA}")
print(f"Identity Matrix I:\n{identity_matrix}")
print(f"Is A . A⁻¹ approximately equal to I? {np.allclose(product_A_invA, identity_matrix)}")

# 2. Prove AB ≠ BA.
product_AB = np.dot(A, B)
product_BA = np.dot(B, A)

print(f"\n2. Proving AB ≠ BA:")
print(f"A . B:\n{product_AB}")
print(f"B . A:\n{product_BA}")
print(f"Is A . B equal to B . A? {np.array_equal(product_AB, product_BA)}")

# 3. Prove (AB)ᵀ = BᵀAᵀ
product_AB_T = np.transpose(product_AB) # or product_AB.T
transpose_B = np.transpose(B) # or B.T
transpose_A = np.transpose(A) # or A.T
product_BT_AT = np.dot(transpose_B, transpose_A)

print(f"\n3. Proving (AB)ᵀ = BᵀAᵀ:")
print(f"(A . B)ᵀ:\n{product_AB_T}")
print(f"Bᵀ . Aᵀ:\n{product_BT_AT}")
print(f"Is (A . B)ᵀ approximately equal to Bᵀ . Aᵀ? {np.allclose(product_AB_T, product_BT_AT)}")

Given matrices:
A = 
[[3 4]
 [7 8]]
B = 
[[5 3]
 [2 1]]

1. Proving A.A⁻¹ = I:
Inverse of A:
[[-2.    1.  ]
 [ 1.75 -0.75]]
A . A⁻¹:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity Matrix I:
[[1. 0.]
 [0. 1.]]
Is A . A⁻¹ approximately equal to I? True

2. Proving AB ≠ BA:
A . B:
[[23 13]
 [51 29]]
B . A:
[[36 44]
 [13 16]]
Is A . B equal to B . A? False

3. Proving (AB)ᵀ = BᵀAᵀ:
(A . B)ᵀ:
[[23 51]
 [13 29]]
Bᵀ . Aᵀ:
[[23 51]
 [13 29]]
Is (A . B)ᵀ approximately equal to Bᵀ . Aᵀ? True


### Solving System of Linear Equations:

In [ ]:
import numpy as np

# Given system of linear equations:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Represent the equations in Matrix form AX = B
# A is the coefficient matrix
A_coeffs = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
])

# B is the constants vector
B_constants = np.array([-1, -3, 9])

print(f"Coefficient Matrix A:\n{A_coeffs}")
print(f"Constants Vector B: {B_constants}")

# Solve using Inverse Method (X = A⁻¹B)
# First, find the inverse of A
inverse_A_coeffs = np.linalg.inv(A_coeffs)
print(f"\nInverse of A:\n{inverse_A_coeffs}")

# Then, multiply A⁻¹ by B
X_inverse_method = np.dot(inverse_A_coeffs, B_constants)
print(f"\nSolution using Inverse Method (x, y, z): {X_inverse_method}")

# Verify the solution by plugging back into A_coeffs * X
print(f"Verification (A * X): {np.dot(A_coeffs, X_inverse_method)}")
print(f"Expected B: {B_constants}")

# Solve using np.linalg.solve function
X_solve_function = np.linalg.solve(A_coeffs, B_constants)
print(f"\nSolution using np.linalg.solve (x, y, z): {X_solve_function}")

# Verify if both methods yield the same result
print(f"Are solutions from both methods approximately equal? {np.allclose(X_inverse_method, X_solve_function)}")

Coefficient Matrix A:
[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
Constants Vector B: [-1 -3  9]

Inverse of A:
[[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]

Solution using Inverse Method (x, y, z): [ 2.  1. -2.]
Verification (A * X): [-1. -3.  9.]
Expected B: [-1 -3  9]

Solution using np.linalg.solve (x, y, z): [ 2.  1. -2.]
Are solutions from both methods approximately equal? True


In [ ]:
# 7. Flatten a List of Lists of Lists (Deep Flatten):
def deep_flatten(lst):

    flattened_list = []
    for item in lst:
        if isinstance(item, list):
            flattened_list.extend(deep_flatten(item))
        else:
            flattened_list.append(item)
    return flattened_list

nested_list_1 = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print(f"Original deeply nested list: {nested_list_1}")
print(f"Deeply flattened list: {deep_flatten(nested_list_1)}")

nested_list_2 = [1, [2, [3, [4, 5], 6]], 7, [8]]
print(f"Original deeply nested list: {nested_list_2}")
print(f"Deeply flattened list: {deep_flatten(nested_list_2)}")

nested_list_3 = []
print(f"Original deeply nested list: {nested_list_3}")
print(f"Deeply flattened list: {deep_flatten(nested_list_3)}")

Original deeply nested list: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
Deeply flattened list: [1, 2, 3, 4, 5, 6, 7, 8]
Original deeply nested list: [1, [2, [3, [4, 5], 6]], 7, [8]]
Deeply flattened list: [1, 2, 3, 4, 5, 6, 7, 8]
Original deeply nested list: []
Deeply flattened list: []


In [ ]:
# 8. Nested List Average:
def average_nested(lst):
    total_sum = 0
    count = 0

    def _sum_and_count(inner_lst):
        nonlocal total_sum, count
        for item in inner_lst:
            if isinstance(item, list):
                _sum_and_count(item)
            elif isinstance(item, (int, float)):
                total_sum += item
                count += 1

    _sum_and_count(lst)

    if count == 0:
        raise ValueError("The nested list is empty or contains no numeric elements to average.")

    return total_sum / count

nested_list_1 = [[1, 2], [3, 4], [5, 6]]
print(f"Original nested list: {nested_list_1}")
print(f"Average of elements: {average_nested(nested_list_1)}")

nested_list_2 = [10, [20, 30], [40, [50]]]
print(f"Original nested list: {nested_list_2}")
print(f"Average of elements: {average_nested(nested_list_2)}")

nested_list_3 = [7]
print(f"Original nested list: {nested_list_3}")
print(f"Average of elements: {average_nested(nested_list_3)}")

nested_list_4 = [1, 'a', [2, 'b', [3, 'c']]]
print(f"Original nested list: {nested_list_4}")
print(f"Average of numeric elements: {average_nested(nested_list_4)}")

try:
    average_nested([])
except ValueError as e:
    print(f"Error for empty list: {e}")

try:
    average_nested([['a', 'b'], ['c']])
except ValueError as e:
    print(f"Error for non-numeric list: {e}")

Original nested list: [[1, 2], [3, 4], [5, 6]]
Average of elements: 3.5
Original nested list: [10, [20, 30], [40, [50]]]
Average of elements: 30.0
Original nested list: [7]
Average of elements: 7.0
Original nested list: [1, 'a', [2, 'b', [3, 'c']]]
Average of numeric elements: 2.0
Error for empty list: The nested list is empty or contains no numeric elements to average.
Error for non-numeric list: The nested list is empty or contains no numeric elements to average.
